import './globals.css'
import type { Metadata } from 'next'
import { FONT_FAMILIES } from '@/utils/constant'
import { Header } from '@/components/templates/header'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={FONT_FAMILIES.default.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
